import { Router } from "express";
import { z } from "zod";

export const exportRouter = Router();

const PdfSchema = z.object({
  markdown: z.string().min(1).max(2_000_000),
  title: z.string().max(200).optional()
});

exportRouter.post("/export/pdf", async (req, res) => {
  const parsed = PdfSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: "Invalid request", details: parsed.error.flatten() });
  const { markdown, title } = parsed.data;

  // Host-only v1: render markdown as preformatted text.
  // Next: add markdown-it styling + code highlighting.
  const safeTitle = (title || "BMADly Document").replace(/[<>]/g, "");
  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${safeTitle}</title>
    <style>
      body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; padding: 28px; }
      h1 { margin: 0 0 12px; font-size: 22px; }
      pre { white-space: pre-wrap; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; font-size: 11px; line-height: 1.45; }
      .meta { color: #64748b; font-size: 12px; margin-bottom: 10px; }
    </style>
  </head>
  <body>
    <h1>${safeTitle}</h1>
    <div class="meta">Generated by BMADly</div>
    <pre>${markdown.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
  </body>
</html>`;

  // Lazy import so backend can still run without playwright installed.
  let chromium: any;
  try {
    ({ chromium } = await import("playwright"));
  } catch {
    return res.status(500).json({ error: "PDF export requires Playwright. Install it in backend." });
  }

  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "load" });
    const pdf = await page.pdf({ format: "A4", printBackground: true });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=\"${(title || "document").replace(/[^a-z0-9_-]+/gi, "-")}.pdf\"`);
    res.send(Buffer.from(pdf));
  } finally {
    await browser.close().catch(() => {});
  }
});

